@BASE_URL = http://localhost:3000/api


###
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "eren@gmail.com",
    "password": "1234"
}
###
GET {{BASE_URL}}/users/662acfac3e0527c1c5a6b16f
###
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "nameSurname": "tessafdsdtsda tsadestasdt",
    "username": "tessadfsadSDASD ASDfsadffasdatasd",
    "email": "test@tesadsaASDAASDdsadffsdfsasdasdt.casdom",
    "password": "test1aasdfsd2asd3"
}
###
PATCH  {{BASE_URL}}/users/662acf963e0527c1c5a6b16d
Content-Type: application/json

{
    "nameSurname": "test tasdfasdfasdfasfdasdfsadestasdt",
    "username": "tessadftASDasd",
    "email": "test@tesadst.ASDADasdfasdfasdfasdfacasdom",
    "password": "test12asdfasdfasfdasdfasdfsd3"
}
###
DELETE {{BASE_URL}}/users/662acf963e0527c1c5a6b16d