@BASE_URL = http://localhost:3000/api


# johndoe@example.com
# janesmith@example.com
# alicejohnson@example.com
# davidbrown@example.com
# emilywilson@example.com
# michaeljohnson@example.com
# sarahadams@example.com
# christopherlee@example.com

### LOGIN
# @name login
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "milywilson@example.com",
    "password": "12345678"
}

### JOIN GROUP
@authToken = {{login.response.body.data}}
POST {{BASE_URL}}/groups/join
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "invitationToken": "292706",
    "mainPosition": "GK",
    "altPosition": "DEF",
    "shirtNumber": 11
}
### GET ALL GROUPS BY USER
GET {{BASE_URL}}/groups
Content-Type: application/json
Authorization: Bearer {{authToken}}

### GET GROUP BY GROUP ID
GET {{BASE_URL}}/groups/663e9a880e7f85f441b17fc1
Content-Type: application/json
Authorization: Bearer {{authToken}}

### CREATE GROUP
@authToken = {{login.response.body.data}}
POST {{BASE_URL}}/groups
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "groupName": "VOTING TEST GROUP",
    "mainPosition": "FWD",
    "altPosition": "DEF",
    "shirtNumber":1
}

### INVATE GROUP
@authToken = {{login.response.body.data}}
POST {{BASE_URL}}/groups/invite
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "groupId": "666345220b51a4b41d9218e7"
}




### LEAVE GROUP
@authToken = {{login.response.body.data}}
POST {{BASE_URL}}/groups/leave
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "userId": "6661bb6e54312e13c9b1005d",
    "groupId": "663e9a880e7f85f441b17fc1"
}

