@BASE_URL = http://localhost:3000/api




### LOGIN
# @name login
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "michaeljohnson@example.com",
    "password": "12345678"
}

### GET ALL GROUPS BY USER
GET {{BASE_URL}}/groups
Content-Type: application/json
Authorization: Bearer {{authToken}}

### GET GROUP BY GROUP ID
GET {{BASE_URL}}/groups/663e9a880e7f85f441b17fc1
Content-Type: application/json
Authorization: Bearer {{authToken}}

### CREATE GROUP
@authToken = {{login.response.body.data}}
POST {{BASE_URL}}/groups
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "groupName": "Avcılar IUC Halısaha",
    "mainPosition": "663e94ae3f58cf748889aaed",
    "altPosition": "663e94ae3f58cf748889aaca",
    "shirtNumber": 8
}

### INVATE GROUP
@authToken = {{login.response.body.data}}
POST {{BASE_URL}}/groups/invite
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "groupId": "663e9a880e7f85f441b17fc1"
}

### JOIN GROUP
@authToken = {{login.response.body.data}}
POST {{BASE_URL}}/groups/join
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "invitationToken": "3a3d457daedeb766b28811438ab47692476f23f3",
    "mainPosition": "663e94ae3f58cf748889ab10",
    "altPosition": "663e94ae3f58cf748889aaca",
    "shirtNumber": 1
}

### LEAVE GROUP
@authToken = {{login.response.body.data}}
POST {{BASE_URL}}/groups/leave
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "userId": "6637ee27b3c1eb3c06cd111d",
    "groupId": "6637f6fdbd2b0d157a8c5328"
}

