@BASE_URL = http://localhost:3000/api

### LOGIN
# @name login
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "muratkaradeniz800@gmail.com",
    "password": "12345678"
}

### PROFILE
@authToken = {{login.response.body.data}}
GET {{BASE_URL}}/users/profile
Authorization: Bearer {{authToken}}

### CREATE MATCH
@authToken = {{login.response.body.data}}
POST {{BASE_URL}}/matches
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "groupId": "666419c4f2c8f16e76acb34a",
    "players": [
        "6664170c931376a7166fff44",
        "666418d67c3e86045de18931",
        "6664194c7c3e86045de18958",
        "6664193b7c3e86045de18952",
        "6664190d7c3e86045de18946"
    ],
    "formation": "1-2-1",
    "matchDate": "2024-06-14T21:00:00.040+00:00",
    "location": "VOTING TEST MATCH"
}

### GET MATCHES BY GROUP
@authToken = {{login.response.body.data}}
GET {{BASE_URL}}/matches/byGroup/663e9a880e7f85f441b17fc1
Authorization: Bearer {{authToken}}


### GET MATCH BY ID
@authToken = {{login.response.body.data}}
GET {{BASE_URL}}/matches/6658a63e957fdc8261e8912a
Authorization: Bearer {{authToken}}