@BASE_URL = http://localhost:3000/api


### Dummy Users
# johndoe@example.com
# janesmith@example.com
# alicejohnson@example.com
# davidbrown@example.com
# emilywilson@example.com
# michaeljohnson@example.com
# sarahadams@example.com
# christopherlee@example.com
###

POST {{BASE_URL}}/otp/send-otp
Content-Type: application/json

{
    "email": "eerenyavas@gmail.com"
}
###
POST {{BASE_URL}}/otp/verify-otp
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "otp": "335526"
}


###

# Şifre Sıfırlama
POST {{BASE_URL}}/otp/reset-password
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "newPassword": "newpassword123"
}

